export default function CountryList()
{
    return [
        {id: '1', country: 'Afghanistan'},
        {id: '2', country: 'Albania'},
        {id: '3', country: 'Algeria'},
        {id: '4', country: 'Andorra'},
        {id: '5', country: 'Angola'},
        {id: '6', country: 'Antigua and Barbuda'},
        {id: '7', country: 'Argentina'},
        {id: '8', country: 'Armenia'},
        {id: '9', country: 'Australia'},
        {id: '10', country: 'Austria'},
        {id: '11', country: 'Azerbaijan'},
        {id: '12', country: 'Bahamas'},
        {id: '13', country: 'Bahrain'},
        {id: '14', country: 'Bangladesh'},
        {id: '15', country: 'Barbados'},
        {id: '16', country: 'Belarus'},
        {id: '17', country: 'Belgium'},
        {id: '18', country: 'Belize'},
        {id: '19', country: 'Benin'},
        {id: '20', country: 'Bhutan'},
        {id: '21', country: 'Bolivia'},
        {id: '22', country: 'Bosnia and Herzegovina'},
        {id: '23', country: 'Botswana'},
        {id: '24', country: 'Brazil'},
        {id: '25', country: 'Brunei'},
        {id: '26', country: 'Bulgaria'},
        {id: '27', country: 'Burkina Faso'},
        {id: '28', country: 'Burundi'},
        {id: '29', country: 'Côte d`Ivoire'},
        {id: '30', country: 'Cabo Verde'},
        {id: '31', country: 'Cambodia'},
        {id: '32', country: 'Cameroon'},
        {id: '33', country: 'Canada'},
        {id: '34', country: 'Central African Republic'},
        {id: '35', country: 'Chad'},
        {id: '36', country: 'Chile'},
        {id: '37', country: 'China'},
        {id: '38', country: 'Colombia'},
        {id: '39', country: 'Comoros'},
        {id: '40', country: 'Congo (Congo-Brazzaville)'},
        {id: '41', country: 'Costa Rica'},
        {id: '42', country: 'Croatia'},
        {id: '43', country: 'Cuba'},
        {id: '44', country: 'Cyprus'},
        {id: '45', country: 'Czechia (Czech Republic)'},
        {id: '46', country: 'Democratic Republic of the Congo'},
        {id: '47', country: 'Denmark'},
        {id: '48', country: 'Djibouti'},
        {id: '49', country: 'Dominica'},
        {id: '50', country: 'Dominican Republic'},
        {id: '51', country: 'Ecuador'},
        {id: '52', country: 'Egypt'},
        {id: '53', country: 'El Salvador'},
        {id: '54', country: 'Equatorial Guinea'},
        {id: '55', country: 'Eritrea'},
        {id: '56', country: 'Estonia'},
        {id: '57', country: 'Eswatini (fmr. "Swaziland")'},
        {id: '58', country: 'Ethiopia'},
        {id: '59', country: 'Fiji'},
        {id: '60', country: 'Finland'},
        {id: '61', country: 'France'},
        {id: '62', country: 'Gabon'},
        {id: '63', country: 'Gambia'},
        {id: '64', country: 'Georgia'},
        {id: '65', country: 'Germany'},
        {id: '66', country: 'Ghana'},
        {id: '67', country: 'Greece'},
        {id: '68', country: 'Grenada'},
        {id: '69', country: 'Guatemala'},
        {id: '70', country: 'Guinea'},
        {id: '71', country: 'Guinea-Bissau'},
        {id: '72', country: 'Guyana'},
        {id: '73', country: 'Haiti'},
        {id: '74', country: 'Holy See'},
        {id: '75', country: 'Honduras'},
        {id: '76', country: 'Hungary'},
        {id: '77', country: 'Iceland'},
        {id: '78', country: 'India'},
        {id: '79', country: 'Indonesia'},
        {id: '80', country: 'Iran'},
        {id: '81', country: 'Iraq'},
        {id: '82', country: 'Ireland'},
        {id: '83', country: 'Israel'},
        {id: '84', country: 'Italy'},
        {id: '85', country: 'Jamaica'},
        {id: '86', country: 'Japan'},
        {id: '87', country: 'Jordan'},
        {id: '88', country: 'Kazakhstan'},
        {id: '89', country: 'Kenya'},
        {id: '90', country: 'Kiribati'},
        {id: '91', country: 'Kuwait'},
        {id: '92', country: 'Kyrgyzstan'},
        {id: '93', country: 'Laos'},
        {id: '94', country: 'Latvia'},
        {id: '95', country: 'Lebanon'},
        {id: '96', country: 'Lesotho'},
        {id: '97', country: 'Liberia'},
        {id: '98', country: 'Libya'},
        {id: '99', country: 'Liechtenstein'},
        {id: '100', country: 'Lithuania'},
        {id: '101', country: 'Luxembourg'},
        {id: '102', country: 'Madagascar'},
        {id: '103', country: 'Malawi'},
        {id: '104', country: 'Malaysia'},
        {id: '105', country: 'Maldives'},
        {id: '106', country: 'Mali'},
        {id: '107', country: 'Malta'},
        {id: '108', country: 'Marshall Islands'},
        {id: '109', country: 'Mauritania'},
        {id: '110', country: 'Mauritius'},
        {id: '111', country: 'Mexico'},
        {id: '112', country: 'Micronesia'},
        {id: '113', country: 'Miami, FL, USA'},
        {id: '114', country: 'Georgia, GA, USA'},
        {id: '115', country: 'Moldova'},
        {id: '116', country: 'Monaco'},
        {id: '117', country: 'Mongolia'},
        {id: '118', country: 'Montenegro'},
        {id: '119', country: 'Morocco'},
        {id: '120', country: 'Mozambique'},
        {id: '121', country: 'Myanmar (formerly Burma)'},
        {id: '122', country: 'Namibia'},
        {id: '123', country: 'Nauru'},
        {id: '124', country: 'Nepal'},
        {id: '125', country: 'Netherlands'},
        {id: '126', country: 'New Zealand'},
        {id: '127', country: 'Nicaragua'},
        {id: '128', country: 'Niger'},
        {id: '129', country: 'Nigeria'},
        {id: '130', country: 'North Korea'},
        {id: '131', country: 'North Macedonia'},
        {id: '132', country: 'Norway'},
        {id: '133', country: 'Oman'},
        {id: '134', country: 'Pakistan'},
        {id: '135', country: 'Palau'},
        {id: '136', country: 'Palestine State'},
        {id: '137', country: 'Panama'},
        {id: '138', country: 'Papua New Guinea'},
        {id: '139', country: 'Paraguay'},
        {id: '140', country: 'Peru'},
        {id: '141', country: 'Philippines'},
        {id: '142', country: 'Poland'},
        {id: '143', country: 'Portugal'},
        {id: '144', country: 'Qatar'},
        {id: '145', country: 'Romania'},
        {id: '146', country: 'Russia'},
        {id: '147', country: 'Rwanda'},
        {id: '148', country: 'Saint Kitts and Nevis'},
        {id: '149', country: 'Saint Lucia'},
        {id: '150', country: 'Saint Vincent and the Grenadines'},
        {id: '151', country: 'Samoa'},
        {id: '152', country: 'San Marino'},
        {id: '153', country: 'Sao Tome and Principe'},
        {id: '154', country: 'Saudi Arabia'},
        {id: '155', country: 'Senegal'},
        {id: '156', country: 'Serbia'},
        {id: '157', country: 'Seychelles'},
        {id: '158', country: 'Sierra Leone'},
        {id: '159', country: 'Singapore'},
        {id: '160', country: 'Slovakia'},
        {id: '161', country: 'Slovenia'},
        {id: '162', country: 'Solomon Islands'},
        {id: '163', country: 'Somalia'},
        {id: '164', country: 'South Africa'},
        {id: '165', country: 'South Korea'},
        {id: '166', country: 'South Sudan'},
        {id: '167', country: 'Spain'},
        {id: '168', country: 'Sri Lanka'},
        {id: '169', country: 'Sudan'},
        {id: '170', country: 'Suriname'},
        {id: '171', country: 'Sweden'},
        {id: '172', country: 'Switzerland'},
        {id: '173', country: 'Syria'},
        {id: '174', country: 'Tajikistan'},
        {id: '175', country: 'Tanzania'},
        {id: '176', country: 'Thailand'},
        {id: '177', country: 'Timor-Leste'},
        {id: '178', country: 'Togo'},
        {id: '179', country: 'Tonga'},
        {id: '180', country: 'Trinidad and Tobago'},
        {id: '181', country: 'Tunisia'},
        {id: '182', country: 'Turkey'},
        {id: '183', country: 'Turkmenistan'},
        {id: '184', country: 'Tuvalu'},
        {id: '185', country: 'Uganda'},
        {id: '186', country: 'Ukraine'},
        {id: '187', country: 'United Arab Emirates'},
        {id: '188', country: 'United Kingdom'},
        {id: '189', country: 'Uruguay'},
        {id: '190', country: 'Uzbekistan'},
        {id: '191', country: 'Vanuatu'},
        {id: '192', country: 'Venezuela'},
        {id: '193', country: 'Vietnam'},
        {id: '194', country: 'Yemen'},
        {id: '195', country: 'Zambia'},
        {id: '196', country: 'Zimbabwe'}
    ]
}